### PR TITLE
Drop i686, add aarch64.

### PR DESCRIPTION
**Pull request by parasense**
- SDK-19.08 dropped i386 [0]
- Currently flathub buildbot seems to only build aarch64 & x86_64.
- Modify the flathub.json file accordingly.

[0] - https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/437

Signed-off-by: Jon Disnard <jdisnard@redhat.com>

### CODE REVIEW

**Comment by parasense** [comment]
I would appreciate if anybody with access to aarch64 hardware could please give this build a whirl.

**Comment by hfiguiere** [comment]
You could as well just remove the file.

**Comment by parasense** [comment]
> You could as well just remove the file.

Yep, totally true. Removing the file works for me.

**Comment by wberrier** [comment]
Huh, I didn't realize -bin tarball had binaries for arm...  Let's give it a whirl and wait for feedback.

**Pull request merged**
