### PR TITLE
Switch to 5.15-23.08 runtime and use OpenSSL 1.1.1

### LINKED ISSUE #63: Internal error: openssl test 0050 failed
Updated to the 1.17.5 and now opening the program I see this error message:

`Internal error: openssl test 0050 failed`

Any idea what's wrong?

Using Linux Mint 20.3 Cinnamon.

### PR DESCRIPTION
**Pull request by MatMaul**
Using OpenSSL 1.1.x fixes error `Internal error: openssl test 0050 failed`, cf #63.

Unfortunately 1.1.x is out of support since recently, but we don't really have a choice for now.

This PR also:
- remove wget since it is in the runtime and I don't get any error about a missing wget
- switch Java to version 8 to improve compatibility, the BR JVM is probably even older than that. Browsing MakeMKV forum hints that it's best to just stay on version 8.

Fixes #63

### CODE REVIEW

**Comment by MatMaul** [comment]
Note regarding OpenSSL 1.1.x being out of support: this will be supported for a very long time I believe by downstream distributions like Debian and RedHat so it's probably not that much of a trouble, we will just have to switch to some downstream source once there are new CVEs around.
Also by the time MakeMKV will probably be fixed.

**Review by michaelkuhn — APPROVED** [review]
LGTM, thanks!

**Comment by michaelkuhn** [comment]
Tests don't seem to be running, trying to close and reopen.

**Comment by MatMaul** [comment]
bot, build com.makemkv.MakeMKV

**Comment by MatMaul** [comment]
bot, build

**Pull request merged**
