### PR TITLE
Bump to 1.17.8

### PR DESCRIPTION
**Pull request by MrTarantoga**
Since old versions don't work anymore after a new one has become available here a bump to the latest one.

### CODE REVIEW

**Comment by Procsiab** [comment]
The build seems failing perhaps because the date on line 48 of `com.makemkv.MakeMKV.appdata.xml` should use the format `30-09-2024` :thinking:

**Comment by MrTarantoga** [comment]
> The build seems failing perhaps because the date on line 48 of `com.makemkv.MakeMKV.appdata.xml` should use the format `2024-09-30` 🤔

Yep, see it in the error message too. Fixed, hope know it runs.

Thank you!

**Comment by Procsiab** [comment]
> > The build seems failing perhaps because the date on line 48 of `com.makemkv.MakeMKV.appdata.xml` should use the format `2024-09-30` 🤔
> 
> Yep, see it in the error message too. Fixed, hope know it runs.
> 
> Thank you!

I just tried to flatpak build locally and it works with your very same YAML and XML files :+1:

**Comment by MrTarantoga** [comment]
> flatpak run --command=flat-manager-client org.flatpak.Builder commit --wait https://hub.flathub.org/api/v1/build/141895
 in dir /var/lib/buildbot-master/master/workers/MasterWorkerUntrusted/Builds/build
 watching logfiles {}
 argv: [b'flatpak', b'run', b'--command=flat-manager-client', b'org.flatpak.Builder', b'commit', b'--wait', b'https://hub.flathub.org/api/v1/build/141895']
 using PTY: True
Committing build https://hub.flathub.org/api/v1/build/141895
Waiting for commit job
Waiting for checks, if any...
Waiting for check: flathub-hooks
/ Job was started
| Running check command
| Check command cd "/tank/repo/builds/141895" && FLAT_MANAGER_BUILD_ID="141895" FLAT_MANAGER_JOB_ID="258925" "/usr/local/bin/flathub-hooks" "review" "-c" "/etc/flathub-hooks.json" exited unsuccessfully: exit status: 1, stderr: [2024-11-03T16:00:56Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| [2024-11-03T16:00:56Z INFO  flathub_hooks::utils] Retrying (1/5) in 1 seconds...
| [2024-11-03T16:00:57Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| [2024-11-03T16:00:57Z INFO  flathub_hooks::utils] Retrying (2/5) in 2 seconds...
| [2024-11-03T16:00:59Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| [2024-11-03T16:00:59Z INFO  flathub_hooks::utils] Retrying (3/5) in 4 seconds...
| [2024-11-03T16:01:03Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| [2024-11-03T16:01:03Z INFO  flathub_hooks::utils] Retrying (4/5) in 8 seconds...
| [2024-11-03T16:01:11Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| [2024-11-03T16:01:11Z INFO  flathub_hooks::utils] Retrying (5/5) in 16 seconds...
| [2024-11-03T16:01:27Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| Error: HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)
| 
| Stack backtrace:
|    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
|    1: <flathub_hooks::config::RegularConfig as flathub_hooks::config::ValidateConfig>::get_build
|    2: flathub_hooks::review::do_review
|    3: flathub_hooks::main
|    4: std::sys_common::backtrace::__rust_begin_short_backtrace
|    5: std::rt::lang_start::{{closure}}
|    6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
|    7: std::panicking::try::do_call
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
|    8: std::panicking::try
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
|    9: std::panic::catch_unwind
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
|   10: std::rt::lang_start_internal::{{closure}}
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
|   11: std::panicking::try::do_call
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
|   12: std::panicking::try
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
|   13: std::panic::catch_unwind
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
|   14: std::rt::lang_start_internal
|              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
|   15: main
|   16: __libc_start_call_main
|              at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
|   17: __libc_start_main_impl
|              at ./csu/../csu/libc-start.c:392:3
|   18: _start
| 
| Check status updated to Failed("Check command cd \"/tank/repo/builds/141895\" && FLAT_MANAGER_BUILD_ID=\"141895\" FLAT_MANAGER_JOB_ID=\"258925\" \"/usr/local/bin/flathub-hooks\" \"review\" \"-c\" \"/etc/flathub-hooks.json\" exited unsuccessfully: exit status: 1, stderr: [2024-11-03T16:00:56Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:56Z INFO  flathub_hooks::utils] Retrying (1/5) in 1 seconds...\n[2024-11-03T16:00:57Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:57Z INFO  flathub_hooks::utils] Retrying (2/5) in 2 seconds...\n[2024-11-03T16:00:59Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:59Z INFO  flathub_hooks::utils] Retrying (3/5) in 4 seconds...\n[2024-11-03T16:01:03Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:01:03Z INFO  flathub_hooks::utils] Retrying (4/5) in 8 seconds...\n[2024-11-03T16:01:11Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:01:11Z INFO  flathub_hooks::utils] Retrying (5/5) in 16 seconds...\n[2024-11-03T16:01:27Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\nError: HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: <flathub_hooks::config::RegularConfig as flathub_hooks::config::ValidateConfig>::get_build\n   2: flathub_hooks::review::do_review\n   3: flathub_hooks::main\n   4: std::sys_common::backtrace::__rust_begin_short_backtrace\n   5: std::rt::lang_start::{{closure}}\n   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13\n   7: std::panicking::try::do_call\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40\n   8: std::panicking::try\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19\n   9: std::panic::catch_unwind\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14\n  10: std::rt::lang_start_internal::{{closure}}\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48\n  11: std::panicking::try::do_call\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40\n  12: std::panicking::try\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19\n  13: std::panic::catch_unwind\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14\n  14: std::rt::lang_start_internal\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20\n  15: main\n  16: __libc_start_call_main\n             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16\n  17: __libc_start_main_impl\n             at ./csu/../csu/libc-start.c:392:3\n  18: _start\n")
\ Job completed successfully
\ Check flathub-hooks has failed
Job failed: {'check_name': 'flathub-hooks', 'build_id': 141895, 'job_id': 258925, 'status': 3, 'status_reason': 'Check command cd "/tank/repo/builds/141895" && FLAT_MANAGER_BUILD_ID="141895" FLAT_MANAGER_JOB_ID="258925" "/usr/local/bin/flathub-hooks" "review" "-c" "/etc/flathub-hooks.json" exited unsuccessfully: exit status: 1, stderr: [2024-11-03T16:00:56Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:56Z INFO  flathub_hooks::utils] Retrying (1/5) in 1 seconds...\n[2024-11-03T16:00:57Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:57Z INFO  flathub_hooks::utils] Retrying (2/5) in 2 seconds...\n[2024-11-03T16:00:59Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:00:59Z INFO  flathub_hooks::utils] Retrying (3/5) in 4 seconds...\n[2024-11-03T16:01:03Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:01:03Z INFO  flathub_hooks::utils] Retrying (4/5) in 8 seconds...\n[2024-11-03T16:01:11Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n[2024-11-03T16:01:11Z INFO  flathub_hooks::utils] Retrying (5/5) in 16 seconds...\n[2024-11-03T16:01:27Z INFO  flathub_hooks::utils] HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\nError: HTTP status client error (401 Unauthorized) for url (https://hub.flathub.org/api/v1/build/141895/extended)\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: <flathub_hooks::config::RegularConfig as flathub_hooks::config::ValidateConfig>::get_build\n   2: flathub_hooks::review::do_review\n   3: flathub_hooks::main\n   4: std::sys_common::backtrace::__rust_begin_short_backtrace\n   5: std::rt::lang_start::{{closure}}\n   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13\n   7: std::panicking::try::do_call\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40\n   8: std::panicking::try\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19\n   9: std::panic::catch_unwind\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14\n  10: std::rt::lang_start_internal::{{closure}}\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48\n  11: std::panicking::try::do_call\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40\n  12: std::panicking::try\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19\n  13: std::panic::catch_unwind\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14\n  14: std::rt::lang_start_internal\n             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20\n  15: main\n  16: __libc_start_call_main\n             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16\n  17: __libc_start_main_impl\n             at ./csu/../csu/libc-start.c:392:3\n  18: _start\n', 'results': None}
program finished with exit code 1
elapsedTime=72.796731

grafik


It seems, my changes are not the problem this time ...

**Comment by Procsiab** [comment]
This seems related to the build system to me. Also, if I try to HTTP get that URL `https://hub.flathub.org/api/v1/build/141895/extended` I get the same 401 authorization error. I am not familiar with Flathub's CI/CD pipeline, so I am not sure what to try next to investigate.

**Comment by MrTarantoga** [comment]
I try to restart the process tomorrow evening. If it does not work, I create an issue.

**Comment by MrTarantoga** [comment]
bot, build com.makemkv.MakeMKV

**Review by michaelkuhn — APPROVED** [review]
LGTM, thanks for preparing this!

**Pull request merged**
