### PR TITLE
Update to 1.14.4

### PR DESCRIPTION
**Pull request by AHappyUser**

### CODE REVIEW

**Comment by wberrier** [comment]
Thanks for the update, I'm currently not in a position to run a quick sanitation check on the test build.

Would you mind?  Assuming there are no issues, I'll happily merge it in.

**Comment by AHappyUser** [comment]
I installed the test build on a Solus GNOME VM and ran it from the Terminal with no errors.

**Comment by wberrier** [comment]
Great, thanks for the pull request and testing.

**Comment by AHappyUser** [comment]
Happy to help.

**Pull request merged**
