### PR TITLE
Bump to 1.17.7

### PR DESCRIPTION
**Pull request by DocKDE**
Since old versions don't work anymore after a new one has become available here a bump to the latest one.

### CODE REVIEW

**Comment by Quppa** [comment]
Can confirm this build works fine - can this be merged? The current release version does not work due to a version check.

**Comment by DocKDE** [comment]
I'd think so. I've successfully used to new build at least.

**Comment by robertu94** [comment]
https://github.com/flathub/com.makemkv.MakeMKV/pull/87 is also a duplicate

**Comment by robertu94** [comment]
@michaelkuhn I think you have commit rights on this.  I've tested the PR here and it works for me.

**Review by michaelkuhn — APPROVED** [review]
Thanks!

**Pull request merged**
